---
title: "Course 3 Week 3"
author: "Tongyan Li"
date: "January 3, 2018"
output: html_document
---

# Question 1

```{r}
## Read in Data
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
download.file(fileUrl, destfile = "./data/housing.csv")
Q1Data <- read.csv("./data/housing.csv")
head(Q1Data)
attach(Q1Data)
agricultureLogical <- ACR==3 & AGS ==6
which(agricultureLogical)
```

# Question 2

```{r}
## Read in Data
picUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg"
z <- tempfile()
download.file(picUrl,z,mode="wb")
pic <- readJPEG(z, native = TRUE)
## Quantile
c(quantile(pic, 0.3), quantile(pic, 0.8))
file.remove(z)
```

# Question 3

```{r}
fileUrl1 <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(fileUrl1, destfile = "./data/GDP.csv")
Q3Data <- read.csv("./data/GDP.csv")
head(Q3Data)

fileUrl2 <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download.file(fileUrl2, destfile = "./data/Education.csv")
Q3DataE <- read.csv("./data/Education.csv")
merged <- merge(Q3Data, Q3DataE, by.x="X", by.y="CountryCode")
nrow(merged)
arranged <- merged%>%
    arrange(desc(Gross.domestic.product.2012))
```


# Question 4

```{r}
merged$Gross.domestic.product.2012 <- as.numeric(as.character(merged$Gross.domestic.product.2012))
OECD <- merged%>%
    filter(Income.Group=="High income: OECD")
mean(OECD$Gross.domestic.product.2012, na.rm = TRUE)

nonOECD <- merged%>%
    filter(Income.Group=="High income: nonOECD")
mean(nonOECD$Gross.domestic.product.2012, na.rm = TRUE)
```

# Question 5

```{r}
merged$cut <- cut(merged$Gross.domestic.product.2012, 
    breaks=c(quantile(merged$Gross.domestic.product.2012, probs = seq(0, 1, by = 0.20), na.rm = TRUE)))
merged$cut
table(merged$cut, merged$Income.Group)
```